PD-194384: fix the SonarQube Security Hotspots
bazaarvoice/Priam pull request #81
Opened 2022-11-01 13:03 UTC by SergiiKryvenko

## Jira Issue
[PD-194384](https://bazaarvoice.atlassian.net/browse/PD-194384)

## What Are We Doing Here?
Fix the SonarQube Security Hotspots

## How to Test and Verify

1. Check out this PR
2. Run: `mvn clean install -DskipTests=true -Ddependency-check.skip=true`
3. Run: `mvn -e verify -Ddependency-check.skip=true -Pdocker`

## Risk Level
`Low`

## Required Testing
`Smoke`, `Regression`

2022-11-03 08:11 UTC, mike-unitskyi requested changes
looks good

2022-11-03 08:11 UTC, mike-unitskyi commented on priam-cass-extensions/src/main/java/com/netflix/priam/cassandra/extensions/PriamStartupAgent.java
> +                logger.error(e.toString());
```suggestion
                                String message = "Failed to obtain startup data from priam, can not start yet. will retry shortly";
                System.out.println(message);
                logger.error(message, e);
```

2022-11-03 11:05 UTC, SergiiKryvenko commented on priam-cass-extensions/src/main/java/com/netflix/priam/cassandra/extensions/PriamStartupAgent.java
> +                logger.error(e.toString());
I did these changes as you advised

2022-11-04 08:33 UTC, mike-unitskyi approved these changes

2022-11-04 08:37 UTC, merged